version: "3.8"
services:
  
  api:
    build:
      dockerfile: dockerfile
      context: ./api
      target: development
    volumes:
      - ./api:/usr/api/src/app
      - ./usr/src/backend/app/node_modules
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229
  
  frontend:
    build:
      dockerfile: dockerfile
      context: ./frontend
      target: development
    command: npm run start
    volumes:
      - ./frontend:/usr/frontend/src/app
      - ./usr/src/frontend/app/node_modules
    ports:
      - 4200:4200
    links:
      - api
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432
  
  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@hosty.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80



