## Development
##
FROM node:latest AS development
WORKDIR /usr/api/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 3000

## Production
##
FROM node:latest AS production
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /usr/src/app
COPY --from=development /usr/src/app .
EXPOSE 3000
CMD ["node", "dist/main"]